apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressnginxs.nebula.io
spec:
  group: nebula.io
  names:
    kind: IngressNginx
    plural: ingressnginxs
    singular: ingressnginx
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              properties:
                compositionRef:
                  description: Reference to a specific composition version
                  properties:
                    name:
                      description: Composition name (e.g., ingress-nginx-v1, ingress-nginx-v2)
                      type: string
                  type: object
                controller:
                  description: Controller configuration
                  properties:
                    replicaCount:
                      description: Number of controller replicas
                      type: integer
                    service:
                      properties:
                        externalTrafficPolicy:
                          default: Local
                          enum:
                            - Local
                            - Cluster
                          type: string
                        type:
                          default: LoadBalancer
                          enum:
                            - LoadBalancer
                            - NodePort
                            - ClusterIP
                          type: string
                      type: object
                  type: object
                createStaticIp:
                  default: false
                  description: Create a static IP for the LoadBalancer
                  type: boolean
                namespace:
                  default: ingress-nginx
                  description: Namespace to deploy ingress-nginx
                  type: string
                project:
                  description: GCP project ID
                  type: string
                providerConfigRef:
                  default: default
                  description: Helm ProviderConfig reference for target cluster
                  type: string
                region:
                  description: GCP region for static IP
                  type: string
                repository:
                  default: https://kubernetes.github.io/ingress-nginx
                  description: Helm repository URL
                  type: string
                staticIpName:
                  description: Name for the static IP resource
                  type: string
                values:
                  description: Additional Helm values to merge
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                version:
                  default: 4.14.2
                  description: Helm chart version
                  type: string
                writeConnectionSecretToRef:
                  type: object
                  description: Write connection secret to this reference
                  properties:
                    name:
                      type: string
                      description: Secret name
                    namespace:
                      type: string
                      description: Secret namespace
              required:
                - project
                - region
              type: object
            status:
              properties:
                staticIpAddress:
                  description: Allocated static IP address
                  type: string
              type: object
